source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NSURLSessionDownloadManager' do
  pod "CKDownloadManager",:subspecs => ['Core','UI/InternalAppInstallUI','Extension/NSURLSessionAdaptor'], :path => "../../"
end

