source 'https://github.com/CocoaPods/Specs.git'

target 'CKDownloadManager_Example' do
  pod "CKDownloadManager", :path => "../../"
end

target 'CKDownloadManager_Tests' do
  pod "CKDownloadManager", :path => "../../"

  pod 'Kiwi'
end
